package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.EdrViewModel
import com.example.ui.components.SectionHeader
import com.example.ui.theme.*

@Composable
fun CustomReportsScreen(viewModel: EdrViewModel) {
    val allQC by viewModel.allQC.collectAsState()
    val allTasks by viewModel.allTasks.collectAsState()

    var selectedSource by remember { mutableStateOf("All Quality Control") }
    var fromDate by remember { mutableStateOf("") }
    var toDate by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    val sources = listOf("All Quality Control", "QC - Wagon", "QC - Locomotive", "QC - Coach", "Departmental Tasks")

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = 16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
        contentPadding = PaddingValues(top = 12.dp, bottom = 40.dp)
    ) {
        item {
            SectionHeader(title = "Custom QC Report Generator", icon = Icons.Default.Description, accentColor = AccentAmber)
        }

        // Generator Config Card
        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = CardDark),
                shape = RoundedCornerShape(10.dp),
                border = androidx.compose.foundation.BorderStroke(1.dp, BorderDark)
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Select parameters to generate filtered Acceptance and Quality Control report:", fontSize = 12.sp, color = TextSecondary)

                    // Source Selector
                    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Text("DATA SOURCE", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = TextMuted)
                        OutlinedTextField(
                            value = selectedSource,
                            onValueChange = { selectedSource = it },
                            modifier = Modifier.fillMaxWidth(),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedContainerColor = InputDark,
                                unfocusedContainerColor = InputDark,
                                focusedTextColor = TextPrimary,
                                unfocusedTextColor = TextPrimary
                            )
                        )
                    }

                    // Date range
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        OutlinedTextField(
                            value = fromDate,
                            onValueChange = { fromDate = it },
                            placeholder = { Text("From (YYYY-MM-DD)", fontSize = 11.sp) },
                            modifier = Modifier.weight(1f),
                            colors = OutlinedTextFieldDefaults.colors(focusedContainerColor = InputDark, unfocusedContainerColor = InputDark, focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary)
                        )
                        OutlinedTextField(
                            value = toDate,
                            onValueChange = { toDate = it },
                            placeholder = { Text("To (YYYY-MM-DD)", fontSize = 11.sp) },
                            modifier = Modifier.weight(1f),
                            colors = OutlinedTextFieldDefaults.colors(focusedContainerColor = InputDark, unfocusedContainerColor = InputDark, focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary)
                        )
                    }

                    Button(
                        onClick = { isGenerated = true },
                        colors = ButtonDefaults.buttonColors(containerColor = AccentAmber, contentColor = BgDark),
                        shape = RoundedCornerShape(6.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.Visibility, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Generate Report View", fontWeight = FontWeight.Bold)
                    }
                }
            }
        }

        if (isGenerated) {
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = CardDark),
                    shape = RoundedCornerShape(10.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, BorderDark)
                ) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                        Text(
                            text = "Report: $selectedSource",
                            fontSize = 15.sp,
                            fontWeight = FontWeight.Bold,
                            color = AccentAmber
                        )
                        Divider(color = BorderDark)

                        if (selectedSource == "Departmental Tasks") {
                            allTasks.forEach { task ->
                                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                    Text("[${task.module.uppercase()}] ${task.description}", fontSize = 12.sp, color = TextPrimary, modifier = Modifier.weight(1f))
                                    if (task.remark.isNotBlank()) Text(task.remark, fontSize = 11.sp, color = AccentAmber)
                                }
                            }
                        } else {
                            val list = when (selectedSource) {
                                "QC - Wagon" -> allQC.filter { it.module == "wagon" }
                                "QC - Locomotive" -> allQC.filter { it.module == "locomotive" }
                                "QC - Coach" -> allQC.filter { it.module == "coach" }
                                else -> allQC
                            }
                            list.forEach { qc ->
                                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                    Text("#${qc.number} (${qc.module.uppercase()}): ${qc.description}", fontSize = 12.sp, color = TextPrimary, modifier = Modifier.weight(1f))
                                    Text(qc.status, fontSize = 11.sp, color = AccentAmber, fontWeight = FontWeight.Bold)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
